# Generated by Django 3.2.8 on 2021-10-14 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=50)),
                ('display_content', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('another_content', models.TextField()),
                ('antoher_image', models.ImageField(upload_to='images')),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 10, 14, 2, 59, 35, 718425, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
