# Generated by Django 3.2.8 on 2021-10-14 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='antoher_image',
            new_name='another_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 3, 49, 18, 800882, tzinfo=utc)),
        ),
    ]
